server:
  port: 8099
spring:
  application:
    name: blog-center

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog-center?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8&characterEncoding=UTF-8&rewriteBatchedStatements=true
    username: root
    password: Lc123456@

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  config: classpath:./logback-spring.xml
  level:
    root: info
  file:
    path: ./${spring.application.name}/logs





